"""added resumeName

Revision ID: f1fc2bad42d5
Revises: 
Create Date: 2026-07-29 23:50:54.939564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1fc2bad42d5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Books_author'), table_name='Books')
    op.drop_index(op.f('ix_Books_description'), table_name='Books')
    op.drop_index(op.f('ix_Books_id'), table_name='Books')
    op.drop_index(op.f('ix_Books_title'), table_name='Books')
    op.drop_table('Books')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Books_pkey'))
    )
    op.create_index(op.f('ix_Books_title'), 'Books', ['title'], unique=False)
    op.create_index(op.f('ix_Books_id'), 'Books', ['id'], unique=False)
    op.create_index(op.f('ix_Books_description'), 'Books', ['description'], unique=False)
    op.create_index(op.f('ix_Books_author'), 'Books', ['author'], unique=False)
    # ### end Alembic commands ###
